# Generated by Django 5.1 on 2024-10-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_registration_payment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
    ]
